### ISSUE TITLE
Can't install from pip README.md not found exception

### ISSUE THREAD

**Issue by fmorato** [mstuttgart/pycep-correios#15]
$ pip3 install pycep-correios
    Collecting pycep-correios
      Downloading pycep-correios-1.1.5.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-9wm2b1ms/pycep-correios/setup.py", line 16, in <module>
            long_description=open('README.md', 'r').read(),
        FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9wm2b1ms/pycep-correios/

Need to update MANIFEST.

**Comment by mstuttgart** [comment]
Thanks! Fixed in version [1.1.6](https://github.com/mstuttgart/pycep-correios/releases/tag/1.1.6)
