### ISSUE TITLE
Create English and others language versions of README.md and Docs

### ISSUE THREAD

**Issue by mstuttgart** [mstuttgart/pycep-correios#27]
- [x] English version of README.MD
- [x] English version of documentation. The docs are build using sphinx. Create a en-US directory in `docs` folder and add docs pages translated to this folder.

**Comment by andersonberg** [comment]
Hi. Can I work in the first part of the issue? Then I can help with the docs later.

**Comment by mstuttgart** [comment]
Hi @andersonberg. Yes, shure! :+1: 

Please, create a REAME.md english version in `docs/pt-BR/README.md` folder.

**Comment by andersonberg** [comment]
PR for english version of README: https://github.com/mstuttgart/pycep-correios/pull/28

**Comment by fedesassone** [comment]
Hello! I can add a Spanish version of the README file if you want to

**Comment by mstuttgart** [comment]
Hi @fedesassone shure! :+1:

**Comment by andersonberg** [comment]
PR for docs in english: https://github.com/mstuttgart/pycep-correios/pull/31
