### ISSUE TITLE
Dúvidas / Sugestões (2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [mstuttgart/pycep-correios#35]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

Php= 5.6, 7.0
S.O = Centos7 // Plesk
Plataforma = magento (se possivel)

**Comment by mstuttgart** [comment]
Olá @PauloBoaventura , tudo bem?

Não entendi bem a sua dúvida (acredito que deve ter ocorrido algum engano), mas vamos lá.

#### Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?

Não. A `pycep-correios` é contruída em `Python` (versão 2.7 e 3.4+) . Ela serve apenas como uma interface para consulta de CEP.

#### Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)

Sim. Estou utilizando a versão mais recente do manual do SigepWeb para construí-la. Qualquer nova regra ou mudança no serviço do SigepWeb será adicionada quando houver disponibilidade de tempo. Apesar de que a `pycep-correios` utiliza apenas o serviço `consultaCEP`, que em si é um serviço muito simples e que não sofre muitas mudanças.

#### Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas...

A biblioteca é código aberto e segue a licença MIT. Em grosso modo, você pode utilizá-la em qualquer projeto, seja ele de código aberto ou código fechado, desde que se respeite o termo da licença.

#### Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

Em relação ao *UPGRADE*, a `pycep-correios` é desenvolvida, na maior parte do tempo, apenas por mim e trabalho nela em minha horas livres. Faço isso como um meio de ajudar a comunidade e também como uma forma de estudo. Sendo assim, quaisquer atualizações e correções serão realizadas quando houver disponibilidade de tempo.

De qualquer forma, a `pycep-correios` é um projeto *open-source*, então sinta-se livre para contribuir seja com código ou sugestões.

Caso não tenha respondido suas dúvidas, por gentileza peço que as formalize de forma mais clara.

**Comment by PauloBoaventura** [comment]
Olá @mstuttgart 

Bom minha dúvida era se esta implementação estava funcionando, de acordo com o PHP 5.6, etc...
Pois no final de 2018 o PHP 5.6 será descontinuado...
Bom...
E o meu problema é colocar um código na plataforma magento 1.9 ou 2.1, que funcione para calculo de frete e que insira o valor deste, no final do pedido.

Se souber algo... Por favor compartilhe!
Abs!
