### ISSUE TITLE
Urllib3 com warning

### ISSUE THREAD

**Issue by allexlima** [mstuttgart/pycep-correios#36]
Olá,

ao rodar 

```python
import pycep_correios

pycep_correios.consultar_cep('69010001')
```

eu obtenho o warning:

```
/home/allex/algorithms/bml_aux_/env/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
INFO:pycep_correios.cliente:Consulta de CEP com sucesso!
```

Embora o eu consigo obter o resultado esparado, esse warning incomoda um pouco. Há alguma maneira de eu contorná-lo?

**Comment by mstuttgart** [comment]
Olá @allexlima, tudo tranquilo?

Este *warning* surgiu agora (antes você conseguia desabilitar a necessidade de possui um certificado para consulta). Uma solução temporária (até eu conseguir encontrar uma solução ideal) é desabilitar este *warning* em seu código. O código é seguinte:

```python 
# Realizamos o import da exception
from requests.packages.urllib3.exceptions import InsecureRequestWarning
import warning

with warnings.catch_warnings():
    # Desabilitamos o warning
    warnings.simplefilter('ignore', InsecureRequestWarning)
    pycep_correios.consultar_cep('69010001')
```

**Comment by allexlima** [comment]
Oi, @mstuttgart, tudo tranquilo!

Ah, sim... entendi. Bem, vou utilizar sua solução, obrigado! :+1:

**Comment by mstuttgart** [comment]
Vlw por usar a lib @allexlima ! Qualquer dúvida é só falar.
