### ISSUE TITLE
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.

### ISSUE THREAD

**Issue by mauriciors** [mstuttgart/pycep-correios#42]
Using pytest returns this warning, I believe it is from the zeep library used by the project

`DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.`

can it stop working in the next version? Tks

**Comment by mstuttgart** [comment]
Hi @mauriciors i will see work in this

**Comment by mstuttgart** [comment]
Corrigido na versão 4.0.0 com a inclusão dos novos metodos de busca.
