### ISSUE TITLE
CEP inválido retornar staus code

### ISSUE THREAD

**Issue by ormenese** [mstuttgart/pycep-correios#43]
Fiz uma busca por um CEP inválido e recebi uma exception. Que tal retornar um status code, ou um dicionário com a mensgem de CEP INVÁLIDO ?

Consultas bem sucedidas podem retornar um status code = 200, caso contrário um status code diferente disso.

**Comment by mstuttgart** [comment]
@ormenese no caso, o status code normalmente é usado em REST API's. No caso dos Correios, ele ainda usam o SOAP, por isso decidi manter a estrutura que ele utilizam. No caso no CEP inválido, basta tratar a Exception que é disparada, liberando a necessidade de verificar o status code em cada requisição

**Comment by ormenese** [comment]
Ok Michell, entendido !!!

Eu tentei usar o exemplo do site de vocês (
https://imasters.com.br/back-end/python-consulta-de-cep-com-pycepcorreios ),
o tratamento da exception parece que não está acontecendo.

Você poderia me ajudar neste assunto ??

Executei o seguinte código dentro do python :
try:
    endereco = pycep_correios.consultar_cep('14140615')
except CEPInvalido as exc:
    print('erro')

Eu imaginava que receberia na tela uma mensagem = erro

Mas recebo o seguinte erro:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pycep_correios/cliente.py",
line 61, in consultar_cep
    endereco = client.service.consultaCEP(formatar_cep(cep))
  File "/usr/local/lib/python3.6/site-packages/zeep/proxy.py", line 45, in
__call__
    kwargs,
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py",
line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py",
line 195, in process_reply
    return self.process_error(doc, operation)
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py",
line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: CEP NAO ENCONTRADO

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/pycep_correios/cliente.py",
line 74, in consultar_cep
    raise excecoes.ExcecaoPyCEPCorreios(message=e.message)
pycep_correios.excecoes.ExcecaoPyCEPCorreios: CEP NAO ENCONTRADO

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
NameError: name 'CEPInvalido' is not defined

Como eu devo tratar a exception ???

Obrigado pela ajuda

André







*Minhas figuras favoritas do folclore brasileiro são a democracia e o
estado laico.*


Em qua., 22 de jan. de 2020 às 11:49, Michell Stuttgart <
notifications@github.com> escreveu:

**Comment by ormenese** [comment]
Acabei deixando assim :

except :
    print('erro')

E tudo ok agora !!!



*Minhas figuras favoritas do folclore brasileiro são a democracia e o
estado laico.*


Em qua., 22 de jan. de 2020 às 12:36, André Ormenese <aormenese@gmail.com>
escreveu:

**Comment by mstuttgart** [comment]
@ormenese dá uma olhada na doc.: https://pycep-correios.readthedocs.io/pt/stable/

Esse post que você passou é bem antigo e algumas coisas no uso da lib mudaram desde então. Aqui você pode ver um exemplo de uso com a Exception: https://pycep-correios.readthedocs.io/pt/stable/usage.html
