### ISSUE TITLE
CEP alterado, mas API retorna "não encontrado"

### ISSUE THREAD

**Issue by ormenese** [mstuttgart/pycep-correios#63]
Em algumas buscas no site dos correios, temos a seguinte resposta : "ATENÇÃO! O CEP 13910-000 FOI ALTERADO CONFORME ABAIXO."
E informa o novo CEP.
Na consulta pela pycep-correios a resposta para este mesmo cep é :"CEP NÃO ENCONTRADO"

É possível um retorno onde traga a mesma resposta do site dos correios ?
Att,
André

**Comment by mstuttgart** [comment]
Ola @ormenese isso ocorre porque o banco de dados de CEP que a PyCep-correios passou a utilizar a partir da versão 4.0.0 é a da ViaCEP (e não mais as do Correios). Ele ainda não deve ter sido atualizada com essas novas modificações. Então, não teria como retornar a mesma resposta até que a base de ceps da ViaCEP seja atualizada tambem, blz?

**Comment by ormenese** [comment]
Obrigado pelo retorno !!!
Só um detalho com relação ao ViaCEP.
Já tentei utilizar esta API, mas se fizer muitas consultas ele acaba
negando acesso, coisa que não percebi no PyCep-correios. Será que teremos
problemas com isso ?

Eu possuo uma base com muitos endereços/CEP que precisam ser atualizados.
Eu até tenho um cache de CEP na minha base, mas é um cache recente, ainda
está em formação. Então vou fazer acesso massivo por um período.

Att,
André

*Minhas figuras favoritas do folclore brasileiro são a democracia e o
estado laico.*


Em sex., 3 de abr. de 2020 às 09:40, Michell Stuttgart <
notifications@github.com> escreveu:

**Comment by mstuttgart** [comment]
Em relação ao ViaCEP negar acesso, eu não sabia - vou averiguar isso. Quando ao webservice anterior dos Correios, ele também possui limitação na quantidade de acessos, embora eu não saiba precisar o quanto 'de cabeça'. Eu tive de trocar para o ViaCEP porque o servidor antigo pertencia ao sigepweb, um serviço que exige contrato (mesmo que o metodo de busca de cep não precise de senha), sendo assim achei melhor desvincular do serviço.

**Comment by Murillomdo** [comment]
eevssf
