### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by eduolijfbr** [mstuttgart/pycep-correios#64]
Linux mint 19
No BASH:
sudo python setup.py install

  File "setup.py", line 15
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by mstuttgart** [comment]
Ola @eduolijfbr tudo bem?

O comando `python setup.py install` funciona normalmente pra mim (o recomendado é instalar a pycep-correios com o `pip`). Qual versão do python você esta usando? A `pycep-correios` tem suporte apenas para o Python3.

**Comment by eduolijfbr** [comment]
Ok o problema é o python2.7.
Agradeço.

Em ter, 7 de abr de 2020 11:05, Michell Stuttgart <notifications@github.com>
escreveu:
