### ISSUE TITLE
raise exceptions.BaseException(message=e.message)

### ISSUE THREAD

**Issue by leonardohaleck** [mstuttgart/pycep-correios#68]
Boa tarde, tudo bem? Vê se voce consegue me ajudar, por favor.

Estou utilizando o pycep_correios.get_address_from_cep no Windows 10 com o seguinte código:

pycep_correios.get

E estou encontrando o seguinte erro:

<img width="604" alt="erro_pycep" src="https://user-images.githubusercontent.com/38009184/83038591-86866980-a013-11ea-8cbf-2acda97ecbb1.PNG">

Obrigado desde já.

**Comment by leonardohaleck** [comment]
Corrigindo o código executado que faltou na primeira mensagem:

pycep_correios.get_address_from_cep('20270270')

**Comment by mstuttgart** [comment]
Olá @leonardohaleck , tudo bem?

Fiz o teste com o comando que você me passou e funcionou normalmente aqui:

![screenshot_1](https://user-images.githubusercontent.com/8174740/83054267-8775c600-a028-11ea-985c-0f7138473db3.png)

Pelo que vi na imagem do erro que você enviou, o erro foi um 'NewConnectionError' da lib urlib. Isso pode ter acontecido pelo servidor estar sobrecarregado ou por erro de conexão da internet no momento da consulta. 

Pra evitar erros assim, eu faço um tratamento de exceção:

```python
from pycep_correios import get_address_from_cep
from pycep_correios.exceptions import BaseException

try:
    endereco = pycep_correios.get_address_from_cep('20270270')
except BaseException as exc:
    print(exec.message)
```
Assim se o erro acontecer, o app não para de funcionar. 

Outro problema pode ser a versão da urllib instalada no seu sistema. O ideial é instalar as libs de python (no caso, a pycep-correios) sempre em um ambiente virtual. Desse modo, dá pra controlar a versão das dependencias da lib.

Por gentileza, teria como você instalar a`pycep-correios`  em um virtualenv e tentar novamente a consulta pra se o erro ocorre novamente? Dê uma olhada também se sua internet esta apresentando problemas de conexão. Se o erro persistir, me avise por favor!
