### ISSUE TITLE
Status code equal to 200 but API return error

### ISSUE THREAD

**Issue by bgmello** [mstuttgart/pycep-correios#69]
`python version: 3.8.2`

`pycep-correios version: 4.0.1`

Pode parecer um bug um pouco bizarro mas se você pesquisar o endereço dado o CEP `20000000` a bibloteca retorna o seguinte erro:

```
KeyError: 'bairro'
```

Fui pesquisar mais a fundo porque isso acontecia e descobri que o link que você está usando para pegar o endereço retorna o seguinte quando uso o CEP 20000000:

```
r = requests.get('http://www.viacep.com.br/ws/20000000/json')
print(r.status_code)
200
print(r.json())
{'erro': True}
```

Logo, apesar de ter ocorrido um erro no GET da API ele retorna `status_code` de sucesso.

Fiz um fork para tentar corrigir isso e basicamente só adiconei um if antes de testar se  `status_code==200`  na função `get_address_from_cep` para checar se `r.json()['error']` é verdadeiro e se for ele gera o `BaseException`

**Comment by mstuttgart** [comment]
Olá @bgmello , primeiramente, obrigado pelas observações!

Realmente, nesse caso a consulta foi bem sucedida (retorno com código 200) mas o CEP em questão não existe. Pode mandar o PR que eu reviso e crio um release com a modificação! :grin: 

Só um detalhe, a 'pycep-correios' atualmente suporta apenas as versões 3.5, 3.6 e 3.7 do Python. Futuramente, pretendo adicionar suporte a versão 3.8.

Obrigado!
