### ISSUE TITLE
Distritos dos bairros

### ISSUE THREAD

**Issue by naanadr** [mstuttgart/pycep-correios#72]
Olá! Primeiramente, o projeto é massa <3

Vocês conhecem o conceito de `distritos` ? Eu procurei mas não achei no site dos correios informações sobre os distritos, eles só informam o bairro, e nem sempre o distrito é o bairro.

Vocês saberiam dizer, onde eu posso encontrar essa informação? (sem ser em um pdf)
Porque eu queria pesquisar por um CEP e pegar a informação de bairro e de distrito.

**Comment by mstuttgart** [comment]
Olá @naanadr , tudo bem?

Que bom que gostou do projeto! :grin: 

Sobre a informação dos distritos, infelizmente não sei onde encontrar. Tanto o _webservice_ do SIGEPWeb (que possui um serviço de consulta de CEP) quando a API do ViaCep (que é o que usamos), provê apenas o nome do bairro. Desde quando iniciei o projeto, sempre estou de olho em outras APIs de endereço, mas nunca encontrei um serviço que faz essa distinção entre bairro e distrito.

**Comment by naanadr** [comment]
Em relação a SP eu encontrei esse [link](https://www.prefeitura.sp.gov.br/cidade/secretarias/saude/vigilancia_em_saude/index.php?p=240960) fornecido pela prefeitura, eles fornecem um arquivo `kmz`, tô pensando em carregar ele com geopandas e usar o nominatim para pegar as coordenadas dos endereços que eu quero, e usar essas coordenadas para ver em qual distrito está o ponto...

Vai ser um trabalho da gota fazer isso kkkk e fiquei na dúvida se não tinha essa informação de distrito em canto nenhum. 
Triste :(

**Comment by mstuttgart** [comment]
É, infelizmente é meio difícil de encontrar esses serviços quando é algo do governo. 
Eu nunca tinha parado pra analisar essa diferença entre 'bairro' e 'distrito', mas caso encontre algo do tipo e que seja um serviço posto aqui! 

Vai ser um desafio fazer o tratamento dos dados como você falou, mas também é uma boa oportunidade de fazer algo do tipo (não deve ter nada do tipo por ai). Boa sorte!

**Comment by naanadr** [comment]
O ruim que seria apenas para a cidade de São Paulo :(
