### ISSUE TITLE
Erro na consulta por cep

### ISSUE THREAD

**Issue by naanadr** [mstuttgart/pycep-correios#73]
Olá (de novo)!

Estava fazendo uns testes aqui e me deparei com uma peculiaridade, as vezes quando consulto um cep com a função `pycep_correios.get_address_from_cep(cep)` ele retorna o erro `AttributeError: 'ConnectionError' object has no attribute 'message'`. 

Isso acontece depois de um tempo consultando ceps, depois o erro some e depois o erro volta. Quando esse erro acontece eu utilizo a função antiga `pycep_correios.consultar_cep(cep)`.

Isso já aconteceu antes? Ou é coisa nova?

**Comment by mstuttgart** [comment]
Oi @naanadr , tudo bem?

Então, eu acredito que na verdade são dois problemas separados. Infelizmente, não é a primeira vez que vejo esse erro: https://github.com/mstuttgart/pycep-correios/issues/68 . Da outra vez pedi para o usuário que abriu a _issue_ me passar mais detalhes, mas como ele não voltou a comentar, achei que fosse um erro isolado.

* Acredito que o servidor do [ViaCEP](https://viacep.com.br/) que usamos na consulta tenha um limite de requisições (apesar de na _doc_ dele não falar nada), por ser gratuito. Baseado no que você comentou, acredito que o limite seja por minuto. É a unica explicação que me vem no momento :thinking: 
* A função `consultar_cep` faz a consulta no webservice dos Correios (que parei de usar por alguns motivos) por isso não ocorre o problema.
* O erro que ocorre quando você ultrapassa o numero de conexões não esta sendo tratado, por isso a mensagem de erro (se for esta mesma a causa).

Assim que tiver um tempo aqui, vou fazer uns testes pra averiguar melhor e já lançar uma correção disso.

**Comment by naanadr** [comment]
Só pra complementar tua suposição sobre o ViaCEP, acho que também está relacionado com a seção do usuário. Porque eu deixei aqui rodando a consulta e ela não voltava a funcionar nem a pau, só quando eu parava o script  e colocava pra executar de novo. 

Continuo usando o `consulta_cep` por enquanto? 

Se precisar de ajuda ai só falar que continuo reportando os bugs kkkk ainda não consegui parar pra olhar o código do projeto, pq esses últimos dias estão loucos, mas eu queria ajudar se possível.

**Comment by mstuttgart** [comment]
Entendi. :thinking: 
Eu utilizo a 'requests' pra fazer o GET lá no servidor do ViaCep, pode ser que o 'requests' salve mesmo algum tipo de cache quando ele faz as requisições. Eu queria fazer alguns testes pra saber se o erro é por limite de requisições mesmo. Se for, dai não tem muito o que fazer, resta apenas tratar a exception 'AttributeError' que ele dispara.

De qualquer modo, pretendo ver isso amanhã e dependendo de como for, já lançar uma correção. Se descobrir mais detalhes que ajudem a debugar o erro me avisa, por favor!  :grin: 

No caso do 'consulta_cep' esta _deprecated_, mas tem o mesmo retorno do método atual, então pode usar ele sim até eu corrigir o bug.

**Comment by mstuttgart** [comment]
@naanadr eu corrigi o erro *AttributeError* (release 4.0.4), porém o problema de conexão parece ser por limitação do servidor mesmo.

Uma solução pra contornar isso é a que utilizamos no sistema da empresa onde trabalho. A solução consiste em criar uma tabela pra funcionar como um 'cache' dos endereços de cada CEP consultado. Assim, quando o CEP já foi pesquisado antes ou a consulta dá errado, buscamos os dados do endereço nessa tabela, fazendo a requisição no servidor apenas em casos em que é a primeira consulta de um dado CEP. 

Pra precaver o sistema de quebrar nesses problemas de conexão, você pode usar a exception *BaseException*

```python
import pycep_correios

try:
    pycep_correios.get_address_from_cep('00112233')
except pycep_correiosBaseException as e:
    ... consulta tabela de cache dos ceps...
```

**Comment by naanadr** [comment]
@mstuttgart fiz uma solução parecida com a tua, eu verifiquei se o CEP ja foi enriquecido e se ele não tinha sido eu consultava na API. Mas se desse erro na consulta, eu partia para a consulta antiga. Desse jeito eu não sobrecarreguei o serviço e reduziu a quantidade de requisição 😃 

De toda forma, obrigada por resolver esse bug doidão o/

**Comment by mstuttgart** [comment]
@naanadr Que bom que você conseguiu resolver! Eu que agradeço por você ter reportado o bug! :+1:
