### ISSUE TITLE
get_cep_from_address fora do ar

### ISSUE THREAD

**Issue by naanadr** [mstuttgart/pycep-correios#74]
Olá 😄 

Passando de novo pra reportar mais um comportamento curioso do ViaCep, não sei se tu sabe kkk, mas do nada o `get_cep_from_address()` fica fora do ar. 

O erro levantado é o `AttributeError` e começou a acontecer isso hoje de tarde 😢 foi bem do nada kkk 

Vi que no `client.py` é realizado uma requisição para a `http://www.viacep.com.br/ws/{}/{}/{}/json` e o site do `viacep` está fora do ar (no momento em que escrevo essa issue).

Isso é comum? Tem outra fonte alternativa?

**Comment by mstuttgart** [comment]
Ola @naanadr tudo bem?

É a primeira ver que vejo ele fora do ar. O pessoal deve ter deixado offline pra dar alguma manutenção.

A unica alternativa rápida é fazer a busca usando a função _**consulta_cep**_ antiga, que ela busca no servidor dos Correios.

**Comment by naanadr** [comment]
Que bizarro, pq no navegador realmente ta funcionando. Mas quando uso o `get_cep_from_address()` ele dar o erro `ConnectionError' object has no attribute 'message'` 😭 😭 

Amanhã vou dar uma olhada nisso, se bloquearam meu IP ou algo assim. Pq preciso muito descobrir o cep de uns endereços aqui kkkk

**Comment by naanadr** [comment]
Não sei o que aconteceu naqueles dias, mas agora está tudo normal. Por via das dúvidas estou persistindo resultados antigos em um banco, não sei se isso seria legal para fazer aqui também 🤔 .

**Comment by mstuttgart** [comment]
Olá @naanadr . 

Então, é uma idea interessante... :thinking:
O que eu posso pensar no caso é fazer com que a lib crie um arquivo com SQlite para armazenar os endereços. Seria uma boa opção pra armazenar os ceps e não ficar dependendo 100% do webservice.

**Comment by naanadr** [comment]
A pessoa poderia informar qual conexão ela quer, ai se a pessoa tiver um postgres no RDS (meu caso) ela passaria as credenciais do banco e pronto. Desse jeito não fica local e caso alguém venha a utilizar em produção com outro banco ela pode :) 

Mas não sei como seria pra adicionar isso, se seria muito trabalho e tal 🤔

**Comment by mstuttgart** [comment]
Olá @naanadr tudo bem?

Eu adicionei um novo serviço de busca de CEP (https://apicep.com/api-de-consulta/) na versão 5.0.0-rc . A ViaCEP se mostrou instável em vários momentos, então achei melhor adicionar mais opções. A consulta nos Correios também esta disponível de modo nativo (ver README para detalhes). Achei interessante te avisar já que você estava enfrentando problemas com a consulta de CEP no ViaCEP 😁

**Comment by naanadr** [comment]
Obrigada por avisar ❤️
