### ISSUE TITLE
get_address_from_cep com erro para o cep 13866042

### ISSUE THREAD

**Issue by ormenese** [mstuttgart/pycep-correios#75]
Quando utilizo a get_address_from_cep para o CEP 13866042, recebo o erro : pycep_correios.exceptions.BaseException: Other error

Quando utilizo a consultar_cep, não obtenho erro, e o endereço é retornado.

**Comment by ormenese** [comment]
A base de dados do VIA CEP estava desatualizada. Fiz a atualização no site dos caras e agora está funcionando.

**Comment by mstuttgart** [comment]
Olá @ormenese tudo certo? Sim, pode ser isso mesmo. O Banco do Via CEP não é tão atualizado quanto os dos Correios, infelizmente.

**Comment by ormenese** [comment]
Por curiosidade, por quê você está migrando do webservice dos correios que é oficial, para o Via CEP ?

**Comment by mstuttgart** [comment]
É porque o webservice dos correios faz parte do serviço do Sigepweb (precisa ter contrato para uso), mesmo ele não pedindo senha de usuário para consultar os CEPs, como ele é listado entre os serviços do sigepweb, eu achei melhor desvincular do serviço. Dai migrei para o do Via CEP por ser gratuito e bastante usado
