### ISSUE TITLE
exceptions.BlockedByFlood()

### ISSUE THREAD

**Issue by vitorcaleixo** [mstuttgart/pycep-correios#81]
Boa tarde, tudo bem?

Estou tentando utilizar essa API para pegar um serie de informações sobre alguns CEPs que tenho, porém, estou encontrando esse problema:

---------------------------------------------------------------------------
BlockedByFlood                            Traceback (most recent call last)
<ipython-input-9-a10df1333dfa> in <module>
----> 1 endereco = pycep_correios.get_address_from_cep(cep)
      2 endereco

~\AppData\Roaming\Python\Python37\site-packages\pycep_correios\client.py in get_address_from_cep(cep, webservice)
     38 
     39     if webservice == WebService.APICEP:
---> 40         return apicep.fetch_address(cep)
     41 
     42 

~\AppData\Roaming\Python\Python37\site-packages\pycep_correios\apicep.py in fetch_address(cep)
     22 
     23             if address['status'] == 400 and address['message'] == "Blocked by flood":
---> 24                 raise exceptions.BlockedByFlood()
     25 
     26             if address['status'] == 404:

BlockedByFlood: 

O código que estou rodando é bem simples:

import pandas as pd
import pycep_correios
from geopy.geocoders import Nominatim

cep = '02538-010'

endereco = pycep_correios.get_address_from_cep(cep)
endereco

Sabe o que pode ser esse erro?

Obrigado

**Comment by mstuttgart** [comment]
@vitorcaleixo olá! Tudo bem?

Erro normalmente ocorre quando fazemos um volume de consultas seguidas no servidor. A API que fornece os dados faz um "bloqueio" temporário de modo a desistimular essa comportamento. No caso, o recomendável é não realizar as consultas via script (no caso, buscar vários CEP seguidos). 

Essa mensagem normalmente desaparece depois de alguns minutos e as consultas voltam a funcionar corretamente.

**Comment by vitorcaleixo** [comment]
Eu precisava fazer uma consulta para uma lista considerável de CEPs, coloquei até um time dentro do programa para que ele não execeda o limite de tempo, mas mesmo assim não dá certo.

O que você aconselha?

Esse código que montei:

import csv
import pycep_correios
from geopy.geocoders import Nominatim
import time

# abre o arquivo csv com os CEPs
with open('ceps.csv') as arquivo_ceps:
    # lê os CEPs do arquivo CSV
    leitor_csv = csv.reader(arquivo_ceps)
    ceps = [row[0] for row in leitor_csv]

# faz uma requisição para a API do ViaCEP para cada CEP
for cep in ceps:
    try:
        # faz a consulta do CEP usando a biblioteca pycep_correios
        endereco = pycep_correios.get_address_from_cep(cep)
        #geolocator = Nominatim(user_agent="test_app")
        #location = geolocator.geocode(endereco['logradouro'] + ", " + endereco['cidade'] + " - " + endereco['bairro'])

        # obtém as informações de endereço
        logradouro = endereco['logradouro']
        cidade = endereco['cidade']
        uf = endereco['uf']
        latitude = None
        longitude = None

        # escreve as informações do CEP, endereço, cidade, UF, latitude e longitude em um arquivo CSV
        with open('ceps_com_info.csv', 'a', newline='') as arquivo_saida:
            escritor_csv = csv.writer(arquivo_saida)
            escritor_csv.writerow([cep, logradouro, cidade, uf, latitude, longitude])

        # pausa por um segundo para evitar exceder o limite de 30 consultas por segundo
        time.sleep(1)
    except Exception as e:
        # se houver um erro na consulta, escreve o CEP e o erro em um arquivo de log
        with open('erros.log', 'a') as arquivo_log:
            arquivo_log.write(f'Erro no CEP {cep}: {str(e)}\n')

Nesse primeiro momento estou usando uma lista com 10 ceps, mesmo assim o código gera esse erro.

**Comment by mstuttgart** [comment]
Nesse caso, eu desaconselho a utilização a lib para busca de CEP em lote. As API que a pycep-correios consome normalmente são utilizadas para preenchimento de CEP em formulários. No caso da busca em lote, provavelmente você vai encontrar esse obstáculos de número de acessos. 

No meu trabalho tivemos uma situação parecida e solução foi buscar uma tabela de CEPs com os dados do endereço e importar e usa a lib apenas quando CEP não estiver cadastrado no sistema.

**Comment by vitorcaleixo** [comment]
Uhmm, blz, vou tentar seguir dessa forma.

Por algum acaso você não tem uma base com CEPS que possa compartilhar, tem?

Obrigado

**Comment by mstuttgart** [comment]
@vitorcaleixo infelizmente não amigo. A base que utilizamos foi comprado pela empresa, então é propriedade dela.
